import { ArrowUpRight, Check, Copy, Download, ArrowRight, SearchX, FileCode2, Image as ImageIcon } from 'lucide-react';
import { Link } from 'react-router-dom';
import { useEffect, useState } from 'react';
import type { ReactNode } from 'react';
import type { Experiment, Figure, Outcome } from '../types';
import { kindLabels, outcomeLabels } from '../lib/research';
import { experimentQuestion, experimentResult } from '../lib/experiment-copy';
import { ArtifactDates } from './ArtifactDates';
export function Status({outcome,label}:{outcome:string;label?:string}){return <span className={`status status-${outcome}`}><span className="status-dot"/>{label||outcomeLabels[outcome as Outcome]||outcome}</span>}
/** The corrected badge sits beside an outcome; it never replaces it. */
export function CorrectedBadge({experiment}:{experiment:Pick<Experiment,'corrected'|'correction'>}){return experiment.corrected?<span className="badge-corrected" title={experiment.correction?.note||'A historical claim for this record was corrected'}><span className="status-dot" aria-hidden="true"/>Corrected</span>:null}
/** Research questions show one of four outcomes; method checks show their kind. */
export function ExperimentStatus({experiment}:{experiment:Pick<Experiment,'kind'|'outcome'|'corrected'|'correction'>}){return <span className="experiment-status">{experiment.kind==='method-check'||!experiment.outcome?<Status outcome="method-check" label={kindLabels['method-check']}/>:<Status outcome={experiment.outcome}/>}<CorrectedBadge experiment={experiment}/></span>}
export function PageHeading({eyebrow,title,description,actions}:{eyebrow:string;title:string;description?:string;actions?:ReactNode}){return <div className="page-heading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1>{description&&<p>{description}</p>}</div>{actions&&<div className="heading-actions">{actions}</div>}</div>}
export function Empty({title='No matching records',detail='Try another search or remove a filter.',action}:{title?:string;detail?:string;action?:ReactNode}){return <div className="empty-state"><SearchX size={32}/><h3>{title}</h3><p>{detail}</p>{action}</div>}
export function CopyLink({label='Copy link'}:{label?:string}){const [done,setDone]=useState(false),[error,setError]=useState(false);useEffect(()=>{if(done){const t=setTimeout(()=>setDone(false),2000);return()=>clearTimeout(t)}},[done]);return <button className="button" onClick={async()=>{try{await navigator.clipboard.writeText(location.href);setDone(true);setError(false)}catch{setError(true)}}}>{done?<Check size={16}/>:<Copy size={16}/>} {done?'Copied':error?'Select the address bar':label}</button>}
export function DownloadLink({href,label,primary=false}:{href:string;label:string;primary?:boolean}){return <a className={`button ${primary?'primary':''}`} href={href} download><Download size={16}/>{label}</a>}
export function ExperimentTable({experiments}:{experiments:Experiment[]}){return <div className="table-wrap"><table className="experiment-table"><thead><tr><th>Question / experiment</th><th>Observed result</th><th>Outcome</th><th>Evidence</th><th><span className="sr-only">Open</span></th></tr></thead><tbody>{experiments.map(e=><tr key={e.id}><td><div className="record-id">{e.id}<span>{e.area}</span></div><Link className="experiment-title" to={`/experiments/${e.id}`}>{experimentQuestion(e)}</Link></td><td><div className="table-result">{experimentResult(e)}</div><ArtifactDates kind="experiment" id={e.id}/></td><td><ExperimentStatus experiment={e}/></td><td><div className="evidence-counts"><Link to={`/experiments/${e.id}?tab=figures`} title={`${e.figureIds.length} figures`}><ImageIcon size={15}/>{e.figureIds.length}</Link><Link to={`/experiments/${e.id}?tab=code`} title={`${e.codeIds.length} code files`}><FileCode2 size={15}/>{e.codeIds.length}</Link></div></td><td><Link className="icon-button" to={`/experiments/${e.id}`} aria-label={`Open ${e.id}`}><ArrowUpRight size={18}/></Link></td></tr>)}</tbody></table></div>}
export function FigureCard({figure}:{figure:Figure}){return <Link className="figure-card" to={`/figures/${figure.id}`}><div className="figure-image"><img src={figure.href} alt={figure.title} loading="lazy"/><span className="figure-page">{String(figure.page).padStart(2,'0')}</span></div><div className="figure-caption"><div><span className="eyebrow">{figure.kind==='register'?'Experiment register':'Research figure'}</span><h3>{figure.title}</h3><ArtifactDates kind="figure" id={figure.id}/></div><ArrowUpRight size={20}/></div></Link>}
export function SectionTitle({title,to,label='View all',aside}:{title:string;to?:string;label?:string;aside?:ReactNode}){return <div className="section-title"><h2>{title}</h2>{to?<Link className="text-link" to={to}>{label}<ArrowRight size={16}/></Link>:aside}</div>}
export function ExperimentChips({ids,limit=8}:{ids:string[];limit?:number}){return <div className="chip-row">{ids.slice(0,limit).map(id=><Link className="chip mono" key={id} to={`/experiments/${id}`}>{id}<ArrowUpRight size={12}/></Link>)}{ids.length>limit&&<span className="muted small">+{ids.length-limit} more linked records</span>}</div>}
