import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route, Link } from 'react-router-dom';
import '@fontsource/manrope/400.css';
import '@fontsource/manrope/500.css';
import '@fontsource/manrope/600.css';
import '@fontsource/manrope/700.css';
import '@fontsource/manrope/800.css';
import '@fontsource/ibm-plex-mono/400.css';
import '@fontsource/ibm-plex-mono/500.css';
import './styles.css';
import { ResearchProvider } from './data';
import { ArtifactDatesProvider } from './artifact-dates';
import { Layout } from './components/Layout';
import { Overview } from './pages/Overview';
import { ExperimentsPage, ExperimentDetailPage } from './pages/Experiments';
import { FiguresPage, FigureDetailPage } from './pages/Figures';
import { CodePage, CodeDetailPage } from './pages/Code';
import { RunsPage, RunDetailPage, WarningsPage, ActivityPage } from './pages/Ledger';
import { Empty } from './components/common';
ReactDOM.createRoot(document.getElementById('root')!).render(<React.StrictMode><BrowserRouter><ResearchProvider><ArtifactDatesProvider><Routes><Route element={<Layout/>}><Route index element={<Overview/>}/><Route path="experiments" element={<ExperimentsPage/>}/><Route path="experiments/:id" element={<ExperimentDetailPage/>}/><Route path="figures" element={<FiguresPage/>}/><Route path="figures/:id" element={<FigureDetailPage/>}/><Route path="code" element={<CodePage/>}/><Route path="code/:id" element={<CodeDetailPage/>}/><Route path="runs" element={<RunsPage/>}/><Route path="runs/:id" element={<RunDetailPage/>}/><Route path="warnings" element={<WarningsPage/>}/><Route path="activity" element={<ActivityPage/>}/><Route path="*" element={<Empty title="This page is not in the notebook" action={<Link className="button primary" to="/">Return to overview</Link>}/>}/></Route></Routes></ArtifactDatesProvider></ResearchProvider></BrowserRouter></React.StrictMode>);
