/** Four research outcomes. "Corrected" is a separate badge, never an outcome. */
export type Outcome = 'success' | 'fail' | 'mixed' | 'unresolved';
/** Method checks audit the campaign's own methods; they carry no research outcome. */
export type ExperimentKind = 'research' | 'method-check';
export interface Correction { note: string; source: string; previousOutcome?: string; previousLabel?: string }
export interface SourceFile { id: string; path: string; language: string; role: string; href: string; originalSha256: string; publicSha256: string; redacted: boolean; lines: number; experimentIds: string[]; referenceType: 'explicit' | 'shared' | 'document' }
export interface SourceRef { sourceId: string; line?: number; label: string }
export interface Experiment { id: string; section: number; area: string; title: string; goal: string; comparison: string; why: string; result: string; kind: ExperimentKind; outcome: Outcome | null; corrected: boolean; correction: Correction | null; reason: string; scope: string; batches: string[]; figureIds: string[]; codeIds: string[]; tableIds: string[]; warningIds: string[]; eventIds: string[]; runIds: string[]; sourceRefs: SourceRef[] }
export interface Figure { id: string; page: number; title: string; goal: string; comparison: string; why: string; outcome: string; scope: string; href: string; experimentIds: string[]; kind: string }
export interface DataTable { id: string; title: string; href: string; rows: number; columns: number; experimentIds: string[]; scope: string }
export interface ResearchWarning { id: string; experimentId: string; severity: 'caution' | 'open' | 'correction' | 'limitation'; title: string; detail: string; status: 'open' | 'documented' | 'resolved' }
export interface ActivityEvent { id: string; date: string; kind: string; title: string; detail: string; experimentIds: string[] }
export interface Run { id: string; jobId: string; account: string; batch: string; seed: string; architecture: string; dataset: string; epochs: number; status: string; testAccuracy: number | null; experimentIds: string[]; logHref?: string; parameters: Record<string, string> }
export interface ResearchData { meta: { title: string; asOf: string; generatedAt: string; snapshotId: string; repositoryCommit: string; stats: { experiments: number; researchQuestions?: number; methodChecks?: number; runs: number; figures: number; areas: number }; outcomeModel?: { outcomes: Record<Outcome, string>; badge: string; kinds: Record<ExperimentKind, string>; mapping: string; partitionAuditCommit: string; masterTableSha256: string }; downloads: { pdf: string; bundle: string; source?: string } }; areas: { id: number; label: string; count: number }[]; experiments: Experiment[]; figures: Figure[]; sources: SourceFile[]; tables: DataTable[]; warnings: ResearchWarning[]; activity: ActivityEvent[]; latest: { experimentId: string; peakSet: number[]; predictedCut: number; bestCut: number; bar: number; cells: { arm: string; cut: number | null; mean: number; sem: number; n: number }[] } }
